Add search result coloring for items rarity > 4
Ascension-Addons/Auctionator pull request #1
Opened 2022-12-05 21:35 UTC by Xan-Asc

Colors search results to match their rarity.  In game tooltips has heirloom and vanity rarity the same color, I've elected to follow the color guide from https://wowpedia.fandom.com/wiki/Quality

![Screenshot 2022-12-05 133338](https://user-images.githubusercontent.com/119889093/205747152-47c6431c-8054-4ac3-9493-cf73f9a90004.png)

The extra ||| at the starts of the lines are apparently from my font choice (calibri), not from this change.

2022-12-06 09:39 UTC, andrew6180 requested changes

2022-12-06 09:39 UTC, andrew6180 commented on Auctionator/AuctionatorScan.lua
> +	local color_table = {
You are redefining this table every time the function is called.

2022-12-06 09:39 UTC, andrew6180 commented on Auctionator/AuctionatorScan.lua
> +		self.itemTextColor = colorScanText(quality)
Why not just `self.itemTextColor = ITEM_QUALITY_COLORS[quality]`

2022-12-06 22:31 UTC, Xan-Asc commented
Updated and removed previous commit.  I didn't realize that table existed

2022-12-07 02:55 UTC, andrew6180 approved these changes

2022-12-07 02:56 UTC, merged